name: ubuntu-cloud-image-changelog
version: '0.2'
base: core20
summary: Helpful utility to generate package changelog between two cloud images
description: |
  Helpful utility to generate package changelog between two cloud images
  using their package manifests.

  Usage:
  ubuntu-cloud-image-changelog --from-manifest manifest1.manifest --to-manifest manifest2.manifest

grade: stable
confinement: strict

apps:
  ubuntu-cloud-image-changelog:
    environment:
      PATH: "$SNAP/usr/bin:$SNAP/bin/:$PATH"
      LC_ALL: "C.UTF-8"
      PERL5LIB: "$SNAP/usr/share/perl5/:$SNAP/usr/share/perl/5.30.0/:$SNAP/usr/lib/x86_64-linux-gnu/perl/5.30.0/"
      DEB_VENDOR: "Ubuntu"
      DPKG_ORIGINS_DIR: "$SNAP/etc/dpkg/origins/"
    command: usr/bin/wrapper
    plugs:
      - network
      - home

parts:
  ubuntu-cloud-image-changelog-wrapper:
    plugin: dump
    source: snap/local
    override-build: |
      chmod +x wrapper
      snapcraftctl build
    organize:
      wrapper: usr/bin/wrapper
    stage:
      - usr/bin/wrapper

  ubuntu-cloud-image-changelog:
    plugin: python
    source: ubuntu_cloud_image_changelog
    stage-packages:
      - dpkg
      - dpkg-dev
      - perl-modules-5.30
    python-packages:
      - pip
      - setuptools
      - wheel
